services:
  owt_db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    restart: always

  owt_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - owt_db
    restart: always

volumes:
  postgres_db:
