# Generated by Django 5.0.1 on 2024-01-19 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message="Le nom d'utilisateur doit avoir au moins 3 caractères."), django.core.validators.RegexValidator(message="Le nom d'utilisateur ne peut contenir que des lettres et des chiffres.", regex='^[a-zA-Z0-9]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BodyMassIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('birthdate', models.DateField()),
                ('initial_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('goal_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_european_unit_measure', models.BooleanField(default=True)),
                ('register_user_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_initial_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owt_api.initialdata')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owt_api.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_record_date', models.DateTimeField(auto_now_add=True)),
                ('weight_value', models.DecimalField(decimal_places=1, max_digits=4)),
                ('body_water', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat_mass', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bone_mass', models.DecimalField(decimal_places=1, max_digits=4)),
                ('muscular_mass', models.DecimalField(decimal_places=1, max_digits=4)),
                ('id_bmi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owt_api.bodymassindex')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owt_api.person')),
            ],
        ),
    ]
