# Generated by Django 5.0.1 on 2024-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
