# Generated by Django 5.0.1 on 2024-01-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0004_alter_person_id_user_delete_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bmi_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owt_api.bodymassindex'),
        ),
        migrations.AddField(
            model_name='person',
            name='weight_records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owt_api.weightrecord'),
        ),
    ]
