# Generated by Django 5.0.1 on 2024-02-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='expires_at',
        ),
    ]
