# Generated by Django 5.0.1 on 2024-01-30 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0004_rename_gender_initialdata_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialdata',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
