# Generated by Django 5.0.1 on 2024-01-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0005_person_bmi_list_person_weight_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bmi_list',
        ),
        migrations.RemoveField(
            model_name='weightrecord',
            name='id_bmi',
        ),
        migrations.RemoveField(
            model_name='weightrecord',
            name='id_person',
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='bmi',
            field=models.DecimalField(decimal_places=1, default=25, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='weight_records',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='owt_api.weightrecord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BodyMassIndex',
        ),
    ]
