# Generated by Django 5.0.1 on 2024-01-23 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0006_remove_person_bmi_list_remove_weightrecord_id_bmi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id_initial_data',
            new_name='initial_data',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_user',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
