# Generated by Django 5.0.1 on 2024-02-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='initial_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_initial_data', to='owt_api.initialdata'),
        ),
    ]
