# Generated by Django 5.0.1 on 2024-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0007_rename_id_initial_data_person_initial_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='weight_records',
        ),
        migrations.AddField(
            model_name='person',
            name='weigth_records',
            field=models.ManyToManyField(related_name='person', to='owt_api.weightrecord'),
        ),
    ]
