# Generated by Django 5.0.1 on 2024-01-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0008_remove_person_weight_records_person_weigth_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='weigth_records',
            new_name='weigths_record',
        ),
    ]
