# Generated by Django 5.0.1 on 2024-01-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0009_rename_weigth_records_person_weigths_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='weigths_record',
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='person',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='owt_api.person'),
            preserve_default=False,
        ),
    ]
