# Generated by Django 5.0.1 on 2024-01-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0010_remove_person_weigths_record_weightrecord_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='owt_api.person'),
        ),
    ]
