# Generated by Django 5.0.1 on 2024-01-20 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4, message='Password too short, must be at least 4 characters long.')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Username must be at least 3 characters long.'), django.core.validators.RegexValidator(message='Username can only contain letters and numbers.', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='bodymassindex',
            name='bmi',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='body_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
