# Generated by Django 5.0.1 on 2024-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owt_api', '0002_alter_appuser_password_alter_appuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initialdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Neutral')], default='M', max_length=1),
        ),
    ]
